export const type = {
  FETCH: 'TODO/FETCH',
  ADD: 'TODO/ADD',
  DELETE: 'TODO/DELETE',
  FILTER: 'TODO/FILTER',
  CHECKED: 'TODO/CHECKED',
  COLOR: 'TODO/COLOR',
  FETCH_FULLFILLED: 'TODO/FETCH_FULLFILLED',
  FETCH_ERROR: 'TODO/FETCH_ERROR',
}
